import React from 'react';
import styles from '../../styles/components/Header.module.scss';
import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';

export const Header = () => {
  return (
    <>
      <Head>
        <title>GISDEV - Great Information System</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/GIS-DEV_logo_final-05.png" />
      </Head>
      <main className={styles.header__main}>
        <div className={styles.header__wrap}>
          <div className={styles.header}>
            <div className={styles.header__logo}>
              <Image
                src={'/GIS-DEV_logo_final-01.png'}
                alt="Logo of the company"
                width={200}
                height={50}
              />
            </div>

            <div className={styles.header__navigation}>
              <Link href={'/'}>
                <a className={styles.active}>HOME</a>
              </Link>
              <Link href={'/About-Us'}>
                <a>ABOUT US</a>
              </Link>
              <Link href={'Services'}>
                <a>OUR SERVICES</a>
              </Link>
              <Link href={'#3'}>
                <a>WORK PROCESS</a>
              </Link>
              <Link href={'#4'}>
                <a>CAREERS</a>
              </Link>
            </div>
            <div className={styles.header__navbar}>
              <h4>CONTACT US</h4>
            </div>
          </div>
        </div>
      </main>
    </>
  );
};
