import React from "react";
import styles from "../../styles/components/Header.module.scss";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import Button from "../Button";

export const Header = () => {
  return (
    <>
      <Head>
        <title>GISDEV - Great Information System</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/GIS-DEV_logo_final-05.png" />
      </Head>
      <main className={styles.header__main}>
        <div className={styles.header__wrap}>
          <div className={styles.header}>
            <div className={styles.header__logo}>
              <Image
                src={"/GIS-DEV_logo_final-01.png"}
                alt="Logo of the company"
                width={200}
                height={50}
              />
            </div>
            <div className={styles.header__navigation}>
              <Link href={"#"}>
                <a className={styles.active}>Home</a>
              </Link>
              <Link href={"#1"}>
                <a>About Us</a>
              </Link>
              <Link href={"#2"}>
                <a>Our Services</a>
              </Link>
              <Link href={"#3"}>
                <a>Work Process</a>
              </Link>
              <Link href={"#4"}>
                <a>Careers</a>
              </Link>
            </div>
            <Button className={styles.header__navbar}>
              <h4>CONTACT US</h4>
            </Button>
          </div>
        </div>
      </main>
    </>
  );
};
